/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Timestamp;
  id: Generated<string>;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Sessions {
  createdAt: Timestamp;
  expiresAt: Timestamp;
  id: Generated<string>;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface Users {
  createdAt: Timestamp;
  email: string;
  emailVerified: boolean;
  id: Generated<string>;
  name: string;
  updatedAt: Timestamp;
}

export interface Games {
  bookDepth: number;
  createdAt: Timestamp;
  endedAt: Timestamp | null;
  engineStrength: number;
  id: Generated<string>;
  moves: any;
  openingKey: string;
  pgn: string;
  playerColor: string;
  result: string | null;
  startedAt: Timestamp;
  trainingMode: string;
  updatedAt: Timestamp;
  userId: string;
}

export interface OpeningProgress {
  completed: boolean;
  createdAt: Timestamp;
  id: Generated<string>;
  lastPlayedAt: Timestamp | null;
  maxStepCompleted: number;
  openingKey: string;
  sanPath: string;
  updatedAt: Timestamp;
  userId: string;
}

export interface Exports {
  createdAt: Timestamp;
  error: string | null;
  fps: number;
  gameId: string | null;
  id: Generated<string>;
  overlays: any;
  status: string;
  thumbnailUrl: string | null;
  updatedAt: Timestamp;
  url: string | null;
  userId: string;
}

export interface Verifications {
  createdAt: Timestamp | null;
  expiresAt: Timestamp;
  id: Generated<string>;
  identifier: string;
  updatedAt: Timestamp | null;
  value: string;
}

export interface DB {
  accounts: Accounts;
  exports: Exports;
  games: Games;
  openingProgress: OpeningProgress;
  sessions: Sessions;
  users: Users;
  verifications: Verifications;
}
